<a href="https://colab.research.google.com/github/LINWOO0099/PANDAS-DF/blob/main/requests.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import requests

url = "https://restcountries.com/v3.1/all"

try:
    response = requests.get(url)

    # Print status code
    print("Status Code:", response.status_code)

    if response.status_code == 200:
        data = response.json()
        print("Total number of countries:", len(data))
    else:
        print("Error: Failed to fetch data from API")

except requests.exceptions.RequestException as e:
    print("Request Error:", e)

Status Code: 400
Error: Failed to fetch data from API

In [30]:
import pandas as pd

# Sample data for countries
sample_data = [
    {"common_name": "United States", "population": 331000000, "region": "Americas", "area": 9834000},
    {"common_name": "Canada", "population": 38000000, "region": "Americas", "area": 9985000},
    {"common_name": "Germany", "population": 83000000, "region": "Europe", "area": 357000},
    {"common_name": "Japan", "population": 126000000, "region": "Asia", "area": 378000},
    {"common_name": "Australia", "population": 25000000, "region": "Oceania", "area": 7692000}
]

# Create DataFrame from sample data
df = pd.DataFrame(sample_data)

print("Sample DataFrame 'df' created successfully.")
display(df.head())
print("DataFrame '10' contains the following columns:")

display(df.head(10))

Sample DataFrame 'df' created successfully.

     common_name  population    region     area
0  United States   331000000  Americas  9834000
1         Canada    38000000  Americas  9985000
2        Germany    83000000    Europe   357000
3          Japan   126000000      Asia   378000
4      Australia    25000000   Oceania  7692000

DataFrame '10' contains the following columns:

     common_name  population    region     area
0  United States   331000000  Americas  9834000
1         Canada    38000000  Americas  9985000
2        Germany    83000000    Europe   357000
3          Japan   126000000      Asia   378000
4      Australia    25000000   Oceania  7692000

In [35]:

region_population = df.groupby("region")["population"].sum()
max_region = region_population.idxmax()

# largest area
largest_country = df.loc[df["area"].idxmax(), "common_name"]

#
print("\nSummary Results:")
print("Region with highest total population:", max_region)
print("Country with the largest area:", largest_country)

Summary Results:
Region with highest total population: Americas
Country with the largest area: Canada